### ISSUE TITLE
[All] Legal considerations

### ISSUE THREAD

**Issue by Uome** [dut-iptv/dut-iptv.github.io#10]
Considering the fact that some TV providers don't seem to be all that keen on KODI add-ons (e.g. [Ziggo](https://community.ziggo.nl/deel-je-tips-en-suggesties-91/kodi-ziggo-go-add-on-voor-kodi-20532/index5.html) ), it may be wise to have a backup of this git/community, don't you agree?

Would a Telegram or Element group be an option?

**Comment by dut-iptv** [comment]
An interesting topic to discuss.

Anyone is able to archive this repo by simply downloading the files or git cloning it to their local system.
I am not planning on using additional communication methods besides Github at this time.

Concerning the legality of the addons/repo:
-This repo does not contain any copyrighted materials. It does not even include the real icons for the different services (the addon downloads the real icons using the icons that are published in the google play store after installation)
-These addons where developed using information supplied by users with a legal right to use the services
-These addons provide interoperabilty with systems (embedded linux for example) that are not supported by the providers themselves and as such are in my understanding protected under European law through Directive 2009/24/EC on the legal protection of computer programs.
-No legal action against developers of comparable addons is known internationally (See Disney, Netflix, various regional broadcasters comparable to KPN/Ziggo/etc.)

Some reading material: 
https://vidstromlabs.com/blog/the-legal-boundaries-of-reverse-engineering-in-the-eu/
https://www.gerrishlegal.com/legal-blog/2020/4/7/reverse-engineering-when-can-users-lawfully-decompile-software
http://curia.europa.eu/juris/document/document.jsf?text=&docid=122362&pageIndex=0&doclang=EN&mode=req&dir=&occ=first&part=1&cid=972439
https://lexinsight.wordpress.com/2020/06/08/achieving-interoperability-through-reverse-engineering-a-defense-to-copyright-infringement/

Besides it would be way easier to slightly change their login procedures, I don't have the time or energy to play a cat and mouse game with all (or any) of the broadcasters. Another option would be to (re)enable VMP which renders the addon unusable on all platforms except android.

**Comment by Uome** [comment]
You did your homework well I see! 

If in the future, the risk of a takedown might increase, let me know. It would be a shame if your work would go to waste.
