### ISSUE TITLE
[All] Feature request - multiple providers

### ISSUE THREAD

**Issue by Uome** [dut-iptv/dut-iptv.github.io#11]
In TVHeadend, it's possible to use DVB-C and DVB-S at the same time. You can set that program up in such a way that - in the case of duplicate channels - only the one with the best image quality will appear in your Live TV channel list.

Would it be possible to create a similar option in this add-on with multiple IPTV providers? By the way, I completely understand that you're busy, and you would give this low to no priority, but I just thought I'd mention it. I appreciate the work you've done already.

**Comment by dut-iptv** [comment]
I love this suggestion and I had some spare time the last couple of days to work on various parts of the addons, so I already started working on this feature, but it is a lot of work to get this properly working. Expect at least a couple of weeks before I can release something concrete.

**Comment by FutureCow** [comment]
Would it also be possible to add stream url(m3u8) from a local TV station?

**Comment by dut-iptv** [comment]
> Would it also be possible to add stream url(m3u8) from a local TV station?

It is possible, but it is not something I will be working on. You could take a look at IPTV merge and point it to the epg.xml and playlist.m3u8 generated by my addons and your own playlist.

I will not be giving support for this though.

https://www.matthuisman.nz/2019/02/iptv-merge-kodi-add-on.html?m=1

**Comment by dut-iptv** [comment]
0.9.128 is available in the main repo and should fix this issue.

If you still encounter this or any other bug please post in #60.

Closing.
