### ISSUE TITLE
[Ziggo] ReplayTV doesn't work

### ISSUE THREAD

**Issue by Nuevocasa** [dut-iptv/dut-iptv.github.io#12]
When I want to replay a program, I get the message when I open a random day on a channel: l ' no replay tv information available' turn off the option to only show the standard channels. I've changed all options, reinstalled the add-on several times.

**Comment by dut-iptv** [comment]
Pleaae select force a refresh of the EPG under settings and try again afterwards. 

This might be related to a V2 or V3 account and caching of the EPG for the wrong type of account, will investigate to prevent this in the future

**Comment by Nuevocasa** [comment]
It won't help. Have the same problem on two different systems. All the other options work great!!

**Comment by Nuevocasa** [comment]
How can I see what account I have? V2 or V3...

**Comment by dut-iptv** [comment]
There is no indicator of the type of account visible in the addon but this is determined automatically by the addon based on the respone when you are loged in to Ziggo. It seems that your account is moved from V2 to V3(/4) if you are on a Next box.

What kind of system are you running on?

Can you please check if there are .json files in the userdata directory of the addon?

See https://kodi.wiki/view/Userdata for the userdata directory location for your system and then look for addon_data/plugin.video.ziggo

For NPO1 there should be a file named lgi_nl_prod_master_nl_000001_019401.json for V3 or 24443942983.json for V2

**Comment by SmashRocket** [comment]
Same error here. lgi_nl_prod_master_nl_000001_019401_replay and I've got a Mediabox Next.

**Comment by dut-iptv** [comment]
I finally came around to fixing up the Ziggo addon and rewriting the addon. Error should be fixed.
Considering it is a major rewrite others bugs could be introduced.
