### ISSUE TITLE
[General] Raspberry Pi - OSMC ImportError: No module named Cryptodome

### ISSUE THREAD

**Issue by Uome** [dut-iptv/dut-iptv.github.io#13]
When trying to install your Ziggo GO add-on on an old RPi 2 running OSMC, I stumbled upon the message:

`Ziggo GO error`

When analysing the log, I spotted the following:

`ImportError: No module named Cryptodome`

I managed to resolve this by running:

`pip install --user pycryptodomex`

**Comment by dut-iptv** [comment]
The crypto module for encrypting your username and password is sourced from the kodi netflix addon and you are correct that it is dependent on pycryptodomex on being installed. On OSMC it is not installed by default. The instructions that are given for running the netflix addon on OSMC which should work for my addons is as follows:

```
sudo apt-get install python-crypto
sudo apt-get install build-essential python-pip
sudo pip install -U setuptools
sudo pip install wheel
sudo pip install pycryptodomex
```

**Comment by dut-iptv** [comment]
Repo Readme updated, closing
