### ISSUE TITLE
[Ziggo] Error when starting live tv

### ISSUE THREAD

**Issue by kersvanbinsbergen** [dut-iptv/dut-iptv.github.io#17]
Hi,

Thanks for your effort.

For your information:

Using mibox s 

Ziggo Replay TV working OK
Ziggo Movie and series XL working OK

But when starting  Ziggo live TV kodi shows me this error:

![16017560665908848364030210640803](https://user-images.githubusercontent.com/35664088/95000967-d2e74480-05c5-11eb-95b2-9a11aafd75f0.jpg)

![16017560978666319375365501717839](https://user-images.githubusercontent.com/35664088/95000974-e4305100-05c5-11eb-879c-b727dbb9fe10.jpg)

**Comment by Nigel1992** [comment]
Duplicate issue

**Comment by dut-iptv** [comment]
I finally came around to fixing up the Ziggo addon and rewriting the addon. Error should be fixed.
Considering it is a major rewrite others bugs could be introduced.
