### ISSUE TITLE
Error when click login Tv anywhere 

### ISSUE THREAD

**Issue by kersvanbinsbergen** [dut-iptv/dut-iptv.github.io#18]
Hi,

Thanks for your effort.

For your information:

Using mibox s 

TV anywhere gives me  this error when i click on login

![16017566472911243851232132746355](https://user-images.githubusercontent.com/35664088/95001104-31f98900-05c7-11eb-9b1b-b2d5b5e97ca1.jpg)

**Comment by dut-iptv** [comment]
Duplicate of #14
