### ISSUE TITLE
[NLZiet] Not working

### ISSUE THREAD

**Issue by Nigel1992** [dut-iptv/dut-iptv.github.io#22]
After updating to .96 and doing a full reset I get the following error upon login:

https://paste.kodi.tv/ukinezoqan.kodi

I noticed the nonce and timestamp variables are not a value but rather the variable name as the value.
{ }
```

26oauth_nonce%3D{nonce}%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D{timestamp}

```
On top of that, I also noticed that for example token_timestamp is not using { }

**Comment by dut-iptv** [comment]
I have been throwing around some changes with nonce, that were unnecessary and have been reversed. 

Try .97

**Comment by jbouwh** [comment]
With .97 I get a new error message.
NameError: global name 'random' is not defined.

The error happens at line 123 where the variable nonce is set.

**Comment by Nigel1992** [comment]
Version .97 gives a new error.


https://paste.kodi.tv/zalofuzira.kodi

**Comment by dut-iptv** [comment]
Sorry, not having access to a account is killing right now.

Try again with .98

**Comment by jbouwh** [comment]
.98 still has an error at line 179 of api.py. The authorisation.get() function says TypeError : NoneType object has no attribute __getitem___.
The error occurs at logon.

**Comment by Nigel1992** [comment]
I can give you access to my account @dut-iptv

**Comment by dut-iptv** [comment]
Thanks for the offer, I will probably have access to NLZiet again by tomorrow through means of my own.

Sorry for the delay. Expect a fix soon

**Comment by Nigel1992** [comment]
> Thanks for the offer, I will probably have access to NLZiet again by tomorrow through means of my own.
> 
> 
> 
> Sorry for the delay. Expect a fix soon

If you need the full HTTP Traffic, I can get you it.

**Comment by dut-iptv** [comment]
It seems that NLziet has changed their login flow from oauth 1.0 to openid. I am in the process of recreating the flow in the addon

**Comment by Nigel1992** [comment]
> It seems that NLziet has changed their login flow from oauth 1.0 to openid. I am in the process of recreating the flow in the addon

Any eta on the fix ? 😜

**Comment by dut-iptv** [comment]
Right now ok?

.99 was succesfully tested on Kodi 18 and 19 Alpha 2.

As always your mileage may vary

**Comment by jbouwh** [comment]
With LibreElec 9.2.5 the plugin works again. Thanx for the update!
Somehow playlist.m3u8 only has the radio streams, not the live tv channels.
Perhaps there is an explaination for this. Reconfiguring iptv and pvr did not do the trick.

**Comment by Nigel1992** [comment]
I can confirm everything works using .99
Tested on LibreELEC 9.2.4

Thanks a ton for your hard work on these plugins.
Is there a way to donate to you using PayPal?

**Comment by dut-iptv** [comment]
Live TV playlist should be addressed in .100 (still way off of calling any of the addons 1.0.0)

Appreciate the offer to donate. 
For multiple reasons (anonymity, legal, on principle) I am not accepting donations.

Everyone's efforts to improve the addons are greatly appreciated

**Comment by jbouwh** [comment]
Thank you, the pvr tv channels are loading correctly again now!

**Comment by dut-iptv** [comment]
Closing this for now.

If any new problems come to light please create a new issue
