### ISSUE TITLE
[T-mobile TV] Certain local channels don't play

### ISSUE THREAD

**Issue by Pukson** [dut-iptv/dut-iptv.github.io#26]
![Screenshot_20201019-113529](https://user-images.githubusercontent.com/13370171/96427786-42cd1000-11ff-11eb-9885-63fab53e4a1c.png)
![Screenshot_20201019-113505](https://user-images.githubusercontent.com/13370171/96427790-452f6a00-11ff-11eb-9b54-cdbb070e1b98.png)

Gives this error when starting a stream

**Comment by dut-iptv** [comment]
New install or just updated?
Please restart kodi once.

Better detection if internal proxy is running will be added to a upcoming version. If not the user will be advised to reboot kodi.

**Comment by Pukson** [comment]
Works now, had to install InputStream. Only thing im noticing. Everything works awesome! But channels like local channels. For example EVA, RTV Baarn etc don't work. When clicking them it doesnt do anything but other channels work just fine

**Comment by dut-iptv** [comment]
I expect you also can't play these channels using the web version of tmobile tv or the mobile apps.

I will see if these channels can be easily filtered

**Comment by Pukson** [comment]
They are viewable on the website or app :)

**Comment by dut-iptv** [comment]
Will look into it

**Comment by Pukson** [comment]
Awesome, if you need any help or info let me know :) I noticed the channels without epg won't start. Channels with epg start normally. Maybe that's the issue, I know it sounds weird

**Comment by dut-iptv** [comment]
That sound like exactly the problem. When playing a live channel the addon tries to retrieve information on the title and other information of the currently playing program. If there is no EPG this probably fails and the channel won't play.

Will investigate further and come up with a solution

**Comment by Pukson** [comment]
Ah good, thanks man. Any way to make a donation? Thanks to you I have t-mobile anywhere on every android TV in the house :).

Maybe an option to force playback when there's no EPG?

**Comment by dut-iptv** [comment]
As stated in #22 I appreciate the offer to donate and am happy to hear you like the addon(s). 
For multiple reasons (anonymity, legal, on principle) I am not accepting donations.

Playback for channels without EPG should be fixed in .103

**Comment by Pukson** [comment]
Awesome! Any idea when it will be released?

**Comment by dut-iptv** [comment]
Was released when I posted. If you don't see it in Kodi yet force Kodi to check for addon updates
