### ISSUE TITLE
[T-Mobile TV] Surround sound as default

### ISSUE THREAD

**Issue by denniedegroot** [dut-iptv/dut-iptv.github.io#27]
Is it possible that surround sound is selected by default instead of stereo? 
Now I have to change the audio per channel. Also after changing the audio channel the sound stops, only a stop/start of the channel will fix it.

Thanks for the plugin and effort!

**Comment by dut-iptv** [comment]
It is certainly possible, most code to accomplish this is already present. I will add it to the list of requests

**Comment by dut-iptv** [comment]
Added in .103

Please enable "Force Surround" from the addon settings

**Comment by denniedegroot** [comment]
Thanks! I just tested it and it works great.
