### ISSUE TITLE
[Ziggo] Can't login anymore

### ISSUE THREAD

**Issue by wvanderwees** [dut-iptv/dut-iptv.github.io#30]
Since a few days the Ziggo app doesn't accept my password anymore.

**Comment by dut-iptv** [comment]
Do you mean the addon by "app"?

If so please be specific about your problem.

-Are you able to login with your username/password on ziggogo.tv?
-Have you selected "change login information" in the addon and input your information?
-If so what is the message you receive?
-Do you own a next box? (this decides if you connect to the v2 or v3 api endpoint in the addon)

**Comment by wvanderwees** [comment]
The problem is that login by the addon app in kodi is not possible anymore.

*	I am still able to login with my username/password on ziggogo.tv
*	I have selected "change login information" in the addon and then I got the message “Check username and password” but is 100% good and is not accepted.
*	Yes I have a Ziggo Mediabox Next.
*	See my kodi.log file attached.

**Comment by wvanderwees** [comment]
[kodi.log](https://github.com/dut-iptv/dut-iptv.github.io/files/5447064/kodi.log)

**Comment by dut-iptv** [comment]
Your kodi.log suggests the settings.db file (in which the addon tries to store your password) is locked by some process which results in a failure to save your user information which the login function in turn is unable to retrieve.

Have you tried restarting your device and trying to change login information again?

**Comment by wvanderwees** [comment]
Ofcourse I restarted my devices several times and  changed the login information without succes. I have the same problem at more devices.

**Comment by mrblond18** [comment]
Same (kind of) problem here. I had Ziggo go working before, but it does not work anymore.

I started with a completely new Kodi config and only loaded the ziggo addon. After filling in my credentials (which do work in browser) kodi states:
Error logging in to Ziggo
Check your username and password

Kodi debug log here (can I enable addon debug logging somehow?):
https://paste.kodi.tv/mojeweloza.kodi

**Comment by dut-iptv** [comment]
@mrblond18 : Are you also on a Next box?

Sounds more and more like a issue with the new Ziggo API endpoint (Next box users)

Would explain why I don't have any errors on the old API endpoint.

I will release a new version of the Ziggo addon with extra debug logging to pinpoint the issue tomorrow.

**Comment by mrblond18** [comment]
Yes, I have a mediabox next. Further, I am trying to access from outside my ziggo internet connection. It used to work a few days back...

**Comment by mrblond18** [comment]
Just tried it at my own ziggo internet connection and problem is exactly the same

**Comment by dut-iptv** [comment]
Please try login again in .110 and report back with a Debug log (no fix yet, but extra logging was enabled to pinpoint the error)

**Comment by mrblond18** [comment]
Here you go: https://paste.kodi.tv/jovamabego.kodi
This time I got a (python) error immediately after entering my credentials, in stead of the message: Error logging in to Ziggo - Check your username and password

Side note: the version number of the ziggo iptv addon was set to 0.9. in stead of 0.9.111 (the same goes for canal digitaal).
Side question: in the github repo it looks like there is only one commit all the time (so only the latest). As if you flush the complete repo when you do a new commit. Why do you do that? This way I can not see what has changed. Do you do this deliberately?

**Comment by dut-iptv** [comment]
Sorry logging itself was bugged. Please try again with .112. You should find the text "ZIGGO DEBUG LOGIN" in your kodi log and after this the sent headers, session url, username/password (please remove from the log before posting) and response from ziggo including the received headers, data and HTTP status code (please remove any personal data from these)

> Side note: the version number of the ziggo iptv addon was set to 0.9. in stead of 0.9.111 (the same goes for canal digitaal).

Fixed

> Side question: in the github repo it looks like there is only one commit all the time (so only the latest). As if you flush the complete repo when you do a new commit. Why do you do that? This way I can not see what has changed. Do you do this deliberately?

Yes this is done deliberately at this point. Keeps disk usage at a minimum at the server i'm using to push updates and because of the high rate of updates in this alpha stage I don't care about tracking changes on GitHub right now. I'm using GitHub at this point more like a anonymous webhosting space for my Kodi repo than as a proper GitHub repo.

Will probably change when I decide the addons are ready for a 1.0 release

**Comment by mrblond18** [comment]
Here you go: https://paste.kodi.tv/olovigapov.kodi

Thanks for the explanations!

**Comment by wvanderwees** [comment]
Here it is:
[kodi.log](https://github.com/dut-iptv/dut-iptv.github.io/files/5467013/kodi.log)

**Comment by dut-iptv** [comment]
Login seem to almost complete, but fails on getting watchlist id because of a sql escape error. Hopefully fixed in latest version.

**Comment by mrblond18** [comment]
That's it, works again, thanks!

**Comment by dut-iptv** [comment]
Good to hear. Tnx for all the logs.

@wvanderwees If everything works on your end please close the issue

**Comment by mrblond18** [comment]
I still do see some weird behavior. I tried it with a completely fresh Kodi config.

After installing the ziggo addon I fill in my credentials.
First time trying to login I get a python error.
Second time I get an error that I should check my username and password
Third time it succesfully logs in
Log here: https://paste.kodi.tv/ratakusuba.kodi

Further, after succesfully loggin in using this fresh config, I have fewer channels available then before. I have an (ubuntu based) install that had the previous version running without problems. I updated the ziggo addon on that install (without having to enter my credentials again) and there the addon works again as well. There I have the Ziggo Sport channels available (and working), which are not available on the fresh install:
Ziggo Sport Select HD
Ziggo Sport Voetbal HD
Ziggo Sport Golf HD
Ziggo Sport Racing HD
Ziggo Sport Docu HD
Ziggo  Sport Extra HD

I do have Ziggo Sport HD on the fresh install.

Maybe some other channels are missing as well, I did not go through them 1 by 1 (these are most important to me :-) ).
Can I supply some loggin somehow?
Should I open another ticket for this issue?

Final question (for now): I can not get the "start from beginning" to work. I tried on both KPN and Ziggo addons (have a subscription on both), but both start at the live position of the program when I choose to start from beginning. Is this a known issue or can you give me advice?

**Comment by dut-iptv** [comment]
Will look into your error at first launch. Could have something to do with downloading of all the required settings/EPG files after first install.

More Ziggo channels where moved away from the minimal EPG. This keeps the EPG download size down for users that don't have an additional subscription besides the standard channels.

If you subscribe to additional channels you should disable "Only minimal channels" in the addon settings and force a EPG download.

Start from beginning is in need of a rewrite, each provider has its own way of implementing this capability and it needs some attention to get it to properly work. Its on the list.

**Comment by mrblond18** [comment]
> More Ziggo channels where moved away from the minimal EPG. This keeps the EPG download size down for users that don't have an additional subscription besides the standard channels.
> 
> If you subscribe to additional channels you should disable "Only minimal channels" in the addon settings and force a EPG download.

That's it, works!

I'll try to wait patiently till you have reworked the "start from beginning". Keep up the good work

**Comment by wvanderwees** [comment]
Yesssss!, it works! You did a great job, thank you very much for your time and the good work.
