### ISSUE TITLE
NLziet replay tv, movie and serie overview broken 0.9.105

### ISSUE THREAD

**Issue by jbouwh** [dut-iptv/dut-iptv.github.io#32]
Replay TV: UnicodeEncodeError
Films: ValueError
Series: UnicodeEncodeError

It seems the nlziet api had some charges that break the menus mentioned above.

**Comment by dut-iptv** [comment]
Fixed in .108

**Comment by jbouwh** [comment]
.108 did not fix the problem

**Comment by jbouwh** [comment]
.112 fixes this error
