### ISSUE TITLE
[feature request] Support for videoland?

### ISSUE THREAD

**Issue by powermarcel10** [dut-iptv/dut-iptv.github.io#35]
Hi, and thanks again for this addon.

Im not sure if it is possible, but if there is a way to add support for videoland, it will be awesome. Offcourse there are drm restrictions, but maybe it can be done the way they did with the Netflix addon.

Just an idea.

Best regards,
Marcel

**Comment by dut-iptv** [comment]
An addon for Videoland is almost certainly possible and was planned, but I'm currently focusing first on building a solid base for the current addons. All providers and current addons use Widevine DRM so there is no difference between those and a Videoland addon.

I will close this for now, but a Videoland addon will remain a possibility for the future
