### ISSUE TITLE
[Ziggo] No EPG data in IPTV simple client for certain channels

### ISSUE THREAD

**Issue by roksrini** [dut-iptv/dut-iptv.github.io#36]
What a wonderful project!
But I have a small problem. When using the Ziggo Go addon, there is no EPG data showing in the Kodi IPTV simple client for some of the channels. This occurs (at least) with: SBS6 HD, Veronica HD / Disney XD, Net5 HD, SBS9 HD.
However after choosing one of these channels, the EPG data for the current program is shown at the beginning of the stream. So I assume the EPG is there but it is only not showing in the Kodi IPTV simple client.
Already deleted all EPG data and forced reloading. Also reinstalled the Ziggo Go addon. But none of these solved the problem.

**Comment by dut-iptv** [comment]
Will investigate.

EPG data when you start a stream is retrieved on the fly from the provider while EPG data in the guide is stored in a XML file that is updated every 12 hours from a second GitHub repo. So it is possible there is a discrapency there.

**Comment by dut-iptv** [comment]
This should be fixed in the next version (.114) which will be released later today.

**Comment by dut-iptv** [comment]
.114 Released. Please update, reload EPG, reboot Kodi and report back

**Comment by roksrini** [comment]
Hello, thank you for the quick response!
Followed your instructions, but now there is no EPG data anymore for any of the channels. 
When restarting Kodi I see a message that the EPG data is being retrieved, but after 1% it seems tot stop and the message is gone.

By the way, when changing to another channel the new stream starts much faster then before. So that is a big improvement.

**Comment by roksrini** [comment]
Follow up. I did some more testing.
On my Windows PC situation is as described in my previous post. 
However, on my android phone it works almost perfect. Now the only (non-hidden) channel I have no EPG data for is Canvas HD.
Perhaps this different behaviour is caused by the following. When updating the addon on Windows, I see that the repository is pointing to version .112. In android I see version .114.

**Comment by roksrini** [comment]
Follow up #2. Some more testing.
I manually downloaded the latest Leia branche for the Ziggo addon (plugin.video.ziggo-0.9.114.zip) and unzipped it. Then in "C:\Users\xxx\AppData\Roaming\Kodi\addons" I renamed the dir "plugin.video.ziggo" to something else, and copied the complete unzipped directory instead.
Now the behaviour in Windows is exactly as on my phone.

In short:
1. Repository.anon.iptv-latest.zip is pointing to the wrong version for Windows.
2. Still one of my channels (Canvas HD) has no EPG data.
3. Last but not least: the addon is working almost perfectly, thank you for your hard work!

**Comment by dut-iptv** [comment]
> 1. Repository.anon.iptv-latest.zip is pointing to the wrong version for Windows.

No it does not, there are no OS specific versions of the addon or the repo. Kodi just caches versions and takes some time to auto-update to new versions of addons. You can force this process by following the instructions on https://www.matthuisman.nz/2019/09/how-to-force-kodi-to-update-add-ons.html

> 2. Still one of my channels (Canvas HD) has no EPG data.

Noted, confirmed on my own install, will investigate

> 3. Last but not least: the addon is working almost perfectly, thank you for your hard work!

Np

**Comment by roksrini** [comment]
Follow up #3.
The missing EPG data for Canvas HD is caused by Ziggo!
In the official Ziggo Go app the EPG data for this channel is also missing, so that explains why it is missing in the kodi addon.

By the way: on my ziggo box the EPG data for Canvas HD is there. Strange.

**Comment by roksrini** [comment]
"1. Repository.anon.iptv-latest.zip is pointing to the wrong version for Windows.
No it does not, there are no OS specific versions of the addon or the repo. Kodi just caches versions and takes some time to auto-update to new versions of addons. You can force this process by following the instructions on https://www.matthuisman.nz/2019/09/how-to-force-kodi-to-update-add-ons.html"

That worked!
This bug can now be closed.
