### ISSUE TITLE
EPG not loading for T-mobile 

### ISSUE THREAD

**Issue by Pukson** [dut-iptv/dut-iptv.github.io#39]
Since yesterday the EPG isn't loading anymore. Tried to reset session, force EPG download and log out and login. Also cleared the EPG but haven't had any luck.

**Comment by dut-iptv** [comment]
Do you mean the Simple IPTV EPG?
Some changes where made to make loading it faster by creating a custom EPG on your device which excludes disabled channels. Could cause the problem.
You should be able to fix it by selecting "Auto setup Kodi IPTV"

**Comment by Pukson** [comment]
Yep that did the trick. Thanks man. Tried everything except that.
