### ISSUE TITLE
Miss some channels from Ziggo

### ISSUE THREAD

**Issue by StrongDutch** [dut-iptv/dut-iptv.github.io#40]
First, thank you for the great program in Kodi
I am very satisfied with your addon for Ziggo GO, but I miss a lot of channels such as the Ziggo racing and Dutch football FOX channels. Is it possible to add them?

**Comment by dut-iptv** [comment]
If you subscribe to additional channels you should disable "Only minimal channels" in the addon settings and force a EPG download.
