### ISSUE TITLE
[All] Feature request - DELTA/Caiway IPTV

### ISSUE THREAD

**Issue by mcmurdy** [dut-iptv/dut-iptv.github.io#42]
Are you planning to add support for more IPTV providers? DELTA/Caiway for instance?
I'm willing to help you if you tell me what you need... (stream urls?)

**Comment by dut-iptv** [comment]
There are no plans to support other Cable/DSL/Fiber beside Ziggo, KPN and Tmobile. Supporting those providers aready takes more time than I have available. About 75% of households in NL are a customer of these providers
