### ISSUE TITLE
[Ziggo] Icon

### ISSUE THREAD

**Issue by atreyuhere** [dut-iptv/dut-iptv.github.io#43]
Hi,

First many thanks for your work on this project.
I wanted to point out the Ziggo Go icon that is downloaded is 'old'. Ziggo changed the icon (to a much cooler one ;)), could you point the download process to the new one?

**Comment by dut-iptv** [comment]
You are right. 

It should now point to the new icon, could be 24 hours and one or two reboots before your Kodi will show the new icon.

**Comment by atreyuhere** [comment]
Nice, thanks!
