### ISSUE TITLE
[ALL] Sorting is case sensitive.

### ISSUE THREAD

**Issue by nazegnl** [dut-iptv/dut-iptv.github.io#46]
The programs list a-z doesn't take capitals into account when sorting the lists. 
 See: 
![image](https://user-images.githubusercontent.com/46371483/100461334-f5c73e00-30c8-11eb-979d-d7ed54eba4df.png)

**Comment by dut-iptv** [comment]
Will be fixed in the next version (no ETA)

**Comment by dut-iptv** [comment]
Please test in 116

**Comment by nazegnl** [comment]
@dut-iptv The sorting in regards of the casing is ok, small thing i noticed is that now it doesn;t take the space into account a character. This way the sorting for the "De " group is a bit odd. If it can take the space into account then it would group all the "De " items togather making it more intuitive when browsing. 

See:
![image](https://user-images.githubusercontent.com/46371483/102724973-94833b00-4313-11eb-8b36-72281abd1854.png)

**Comment by dut-iptv** [comment]
Will be fixed in 117

**Comment by nazegnl** [comment]
@dut-iptv Thnx ! Also noticed that the characters like á or é will appear at the bottom of the list.

**Comment by dut-iptv** [comment]
Should also be fixed in 119 and up (currently in the beta repo)

**Comment by dut-iptv** [comment]
0.9.128 is available in the main repo and should fix this issue.

If you still encounter this or any other bug please post in #59.

Closing.
