### ISSUE TITLE
[ALL] December month is not showing right.

### ISSUE THREAD

**Issue by nazegnl** [dut-iptv/dut-iptv.github.io#48]
It seems that the December month is not showing right in the UI. 

See:
![image](https://user-images.githubusercontent.com/46371483/102621438-d65b8800-413f-11eb-9859-7bb02f4eaacc.png)

**Comment by dut-iptv** [comment]
Fixed in 116

**Comment by nazegnl** [comment]
@dut-iptv the sorting in regards of the casing is ok now. Small detail now is that it does not take space charater into account. 
One might expect that it treats the space char as a separate one grouping the ones with "De " together. 
See:
![image](https://user-images.githubusercontent.com/46371483/102724383-84695c80-430f-11eb-9023-320c8ae283f0.png)
