### ISSUE TITLE
[All] Addon werkt niet met kodi 19 op chromebook: "Proxy is niet goed gestart"

### ISSUE THREAD

**Issue by powermarcel10** [dut-iptv/dut-iptv.github.io#53]
Hi! Op mijn chromebook krijg ik helaas constant de volgende melding als ik een stream probeer te starten: "Proxy is niet goed gestart." Een herstart verhelpt dit helaas niet.

Het gebeurd zowel binnen de iptv simple addon als in de addon zelf.. Heb je enig idee hoe ik dit kan oplossen? Ik gebruik versie 0.9.116+

**Comment by powermarcel10** [comment]
Ook op mijn Windows pc krijg ik deze melding met kodi 19 beta 2....

**Comment by simon-kox** [comment]
Ik gebruik Kodie 18.7 op Rapberry Pi en krijg dezelfde error.

**Comment by dut-iptv** [comment]
Please post your issue in English.

Will be fixed in 117

**Comment by powermarcel10** [comment]
Allright great! Thanks for letting us know.

**Comment by dut-iptv** [comment]
This bug was reproduced and fixed in 0.9.122 which is currently available in the beta repository.

0.9.122 will probably be available in the main repository in a couple of days.

**Comment by dut-iptv** [comment]
0.9.128 is available in the main repo and should fix this issue.

If you still encounter this or any other bug please post in #59.

Closing.
