### ISSUE TITLE
[Ziggo] PVR Reminders in Matrix result in freeze

### ISSUE THREAD

**Issue by atreyuhere** [dut-iptv/dut-iptv.github.io#54]
Version .119
Kodi Version 19b2nightly

Issue
After setting a reminder from the guide in a Ziggo Go channel, Kodi will freeze up the moment autos witch is initiated. After restarting Kodi, reminders will continue to spam the screen until reminders are cancelled (deleted) 

Reproduce 
- Open guide and set a timer for a program in the future 
- Start watching another channel or play anything else 
- wait for the actual switch to take place

Right after this moment, Kodi will instantly freeze and cannot recover. Restart required 
After restart, reminders will continue to pop up until removed. If a 'new' switch timer is confirmed or auto triggered, process repeats.

This issue does not occur on other PVR backends, butight very well have something to do with the wip on Kodi, not sure.

**Comment by dut-iptv** [comment]
Seems like a bug in SimpleIPTV.

Please post your issue at their GitHub

**Comment by atreyuhere** [comment]
Will do, thank you!
