### ISSUE TITLE
[All] Proxy setting error

### ISSUE THREAD

**Issue by simon-kox** [dut-iptv/dut-iptv.github.io#55]
Ten eerste bedankt voor het maken van de add-on!

Ik krijg een error dat de proxy settings niet goed zijn afgesteld.

Het zou echt te gek zijn om Ziggo op mijn Raspberry te laten werken via Kodi want de stream werkt voor geen meter via de Chromium Widevine install.

**Comment by simon-kox** [comment]
Ik vind het vet jammer dat het niet werk!!!

**Comment by powermarcel10** [comment]
Waarschijnlijk gebruik je nu een versie die eindigt op .116 Klopt dat? Dit gaf bij mij hetzelfde probleem. Terug gegaan naar versie .115 en het werkte weer.. Welke kodi versie draai je?

**Comment by powermarcel10** [comment]
https://github.com/dut-iptv/dut-iptv.github.io/tree/master/old/leia

Ik zie dat je kodi 18 draait. Hierboven kun je de oudere versie downloaden..

**Comment by dut-iptv** [comment]
Please post your issues in English.

Duplicate of #53 

Proxy will be fixed in 117 which will be released in the upcoming week.

**Comment by simon-kox** [comment]
Thank you!

**Comment by dut-iptv** [comment]
This bug was reproduced and fixed in 0.9.122 which is currently available in the beta repository.

0.9.122 will probably be available in the main repository in a couple of days.

**Comment by dut-iptv** [comment]
0.9.128 is available in the main repo and should fix this issue.

If you still encounter this or any other bug please post in #59.

Closing.
