### ISSUE TITLE
[All] General feedback thread for 0.9.128 and up

### ISSUE THREAD

**Issue by dut-iptv** [dut-iptv/dut-iptv.github.io#59]
All addons have had major parts of the code rewritten.
No support will be given starting now on issues for any version below 0.9.128.

Addons should be more reliable and a lot faster.
Instead of one proxy per addon, all addons now share one proxy.
All background data usage was removed, so you can safely install the new versions on a metered connection.

Note that a reset of the addon settings/profile will be automatically executed on first boot.
This means you will need to relogin and reconfigure the addon after updating.

Also note that all Simple IPTV functionality was moved to the "Dut-IPTV Simple IPTV Connector" addon.
You will need to install this addon from the repository and set this up separately to continue using the addons in IPTV Simple PVR.

Please post any general issues in 0.9.128 and up in this thread.
For Dut-IPTV Simple IPTV Connector specific issues use the separate issue #60

**Comment by atreyuhere** [comment]
I think this refactoring / restructuring is a great step for both users and development.
I am really impressed by the work you do, cheers!

**Comment by powermarcel10** [comment]
Thanks for all your work! It is getting better and better. Also catchup is working fine now. Briliant.

Only on my Chromebook something strange is happening. After Kodi starts I'm able to watch a channel using your addon. When I stop the stream and start the stream again (or another one) Kodi crashes imediatly. It happens all the time. I have tried to create a bug report, but because Kodi crashes, I'm not able to create a proper log file using my chromebook. Do you have any idea? I'm currently not able to test it on windows as im not at home for a couple of days.

**Comment by dut-iptv** [comment]
@atreyuhere @powermarcel10  Tnx, appreciated

@powermarcel10 As you mention catchup can I assume you are running Kodi 19 Beta 2 on your Chromebook?

Might be a Kodi Matrix or Inputstream Adaptive Matrix bug on Chromebook?
Could you try in Kodi 18.9?

My testing environment consists of the following:
-Kodi 19 latest beta on Windows 10 x64
-Kodi 18.9 on Windows 10 x64
-Kodi 18.9 on Nvidia Shield TV running latest Android TV
-Kodi 18.9 on various Amlogic Chinese TV boxes running CoreElec 9.2.5

I have not noticed the behaviour you described on any of these platforms.

I am able to test all addons except for CanalDigitaal as I don't have access to  a subscription or a friend with a subscription that can run tests for me. I also am unable to test the Ziggo V3 endpoint.

**Comment by powermarcel10** [comment]
I'm using Kodi 19 beta 2 on my chromebook indeed. When I am home I will try it on my Windows 10 HTPC. Might be an android/chromebook specific bug indeed.

Since version 132 I'm not able to enter movies, series and other othems like searchresults in the Ziggo and the T Mobile app.. I'm getting this:

**Comment by dut-iptv** [comment]
ZipFile processing related. Should be fixed in 138

**Comment by powermarcel10** [comment]
> ZipFile processing related. Should be fixed in 138

Sory, still the same...

**Comment by powermarcel10** [comment]
Tried version 139, still errors when I try to open movies, series or others categories. Only live tv and replaytv is working. I did a clean install

**Comment by dut-iptv** [comment]
Its Kodi 19 with python 3 vs Kodi 18 with python 2 drama. 

Removing the fixbadzipfile line from /resources/lib/base/l5/api.py on line 359 should fix it for Kodi 19.

Will work on a better solution when I'm back from work tonight.

**Comment by powermarcel10** [comment]
> @atreyuhere @powermarcel10 Tnx, appreciated
> 
> @powermarcel10 As you mention catchup can I assume you are running Kodi 19 Beta 2 on your Chromebook?
> 
> Might be a Kodi Matrix or Inputstream Adaptive Matrix bug on Chromebook?
> Could you try in Kodi 18.9?
> 
> My testing environment consists of the following:
> -Kodi 19 latest beta on Windows 10 x64
> -Kodi 18.9 on Windows 10 x64
> -Kodi 18.9 on Nvidia Shield TV running latest Android TV
> -Kodi 18.9 on various Amlogic Chinese TV boxes running CoreElec 9.2.5
> 
> I have not noticed the behaviour you described on any of these platforms.
> 
> I am able to test all addons except for CanalDigitaal as I don't have access to a subscription or a friend with a subscription that can run tests for me. I also am unable to test the Ziggo V3 endpoint.

I tried the netflix addon that also uses inputstream adaptive, and I'm having the same issues where a second play will crash Kodi. So that has nothing to do with your addon.

**Comment by dut-iptv** [comment]
@powermarcel10 If the problem exists in major addons such as Netflix on a major platform such as ChromeOS it will probably be fixed before the final version of Kodi 19

**Comment by dut-iptv** [comment]
Closing this issue as discussion is mainly being done in #60
