### ISSUE TITLE
Feedback thread for 0.9.128 and up

### ISSUE THREAD

**Issue by dut-iptv** [dut-iptv/dut-iptv.github.io#60]
The Dut-IPTV Simple IPTV Connector addon is a new Kodi program addon that will allow you to create a custom TV and radio channel list and EPG for use with the IPTV Simple PVR addon.

You can create any combination of channels from all my addons that you have installed and are logged in to. You can also change the order of channels and select different video addons for live and replay TV per channel.

To setup the addon:
-Install the addon from the repo
-Install any video addon from the repo for which you have a subscription
-Login to any video addon from the repo for which you have a subscription
-Disable/Enable your favorite channels per video addon through "Settings" -> "Channel Selection" from the menu of each video addon
-Open the Dut-IPTV Simple IPTV Connector addon from the Kodi Program Addons section
-Follow the wizard

The Dut-IPTV Simple IPTV Connector works best in Kodi 19 (Beta 2 and up) because of the support for playing finished programs from the guide (Catchup).

Please post Dut-IPTV Simple IPTV Connector specific issues in this thread.
For any general issues in 0.9.128 and up use the separate issue #59

**Comment by atreyuhere** [comment]
Thanks again for creating this solution for archive playback.
Seems to work well for the limited testing i was able to do.

Wandering if the option to ' force EPG download' will be available again or is it strippped out?

**Comment by maffiabaas** [comment]
Thanks For the update! T-Mobile works For me, but i cant login with my Ziggo login. 
![1610461448307531600878511037493](https://user-images.githubusercontent.com/77290177/104326663-431d3480-54ea-11eb-8708-8754f8bb3877.jpg)

**Comment by dut-iptv** [comment]
@atreyuhere

It was removed because it does not serve a purpose anymore. 
epg.zip files for each enabled provider with separate xml files per channel are download by a service run from the Dut-IPTV Simple IPTV Connector addon every 12 hours. 
Each XML file (5-10 MB in size) includes the EPG data for the previous 7 and the upcoming 7 days for the channel.
The XML files from each channels is combined into one big epg.xml based on your preferences.
IPTV Simple loads this combined epg.xml into the PVR database.

**Comment by dut-iptv** [comment]
@maffiabaas 

Your log does not give any information on what is going on.
Directory/MediaWindow errors don't really mean anything.

When you input your username and password what is the output on screen from the addon?
And do you own a Ziggo Next box? (which means your account connects to the V3/V4 endpoint)

**Comment by maffiabaas** [comment]
> @maffiabaas
> 
> Your log does not give any information on what is going on.
> Directory/MediaWindow errors don't really mean anything.
> 
> When you input your username and password what is the output on screen from the addon?
> And do you own a Ziggo Next box? (which means your account connects to the V3/V4 endpoint)

It says: " controleer je gebruikersnaam en wachtwoord" . Fout bij het inloggen bij Ziggo. I have a Ziggo next box but not on the same IP, if that is what your mean.

**Comment by atreyuhere** [comment]
> @atreyuhere
> 
> It was removed because it does not serve a purpose anymore.
> epg.zip files for each enabled provider with separate xml files per channel are download by a service run from the Dut-IPTV Simple IPTV Connector addon every 12 hours.
> Each XML file (5-10 MB in size) includes the EPG data for the previous 7 and the upcoming 7 days for the channel.
> The XML files from each channels is combined into one big epg.xml based on your preferences.
> IPTV Simple loads this combined epg.xml into the PVR database.

Clear explanation, thank you

**Comment by dut-iptv** [comment]
@maffiabaas 

This means your are on the V3/V4 endpoint. 
Which is different from the V2 endpoint on which I can test (no Next box).
Where you able to login using my addons before?

**Comment by maffiabaas** [comment]
> @maffiabaas
> 
> This means your are on the V3/V4 endpoint.
> Which is different from the V2 endpoint on which I can test (no Next box).
> Where you able to login using my addons before?

Yes until a few weeks back it worked.

**Comment by J-o-h-n-M** [comment]
![image](https://user-images.githubusercontent.com/8143724/104332395-6cd95a00-54f0-11eb-9330-c13cb8dbf606.png)

Can you explain this question. I really have no idea what you mean here.

**Comment by powermarcel10** [comment]
As a suggestion;

It will be very nice if you can add a universal provider option where you can add your universal iptv subscription using xcodes or an  m3u url. I am using a paid iptv subscription from tnci. In the iptv simple addon from kodi it is not possible to add multiple providers. So it will be very nice if your addon can provide this functionallity.

**Comment by J-o-h-n-M** [comment]
I can watch channels in the KPN addon itself now, but when trying to configure the connector. I get a Yes/No question. But it does not say what the question is. But I can select yes or no, I always get the error that you see.

![IMG_20210112_162456](https://user-images.githubusercontent.com/8143724/104335993-38679d00-54f4-11eb-9d35-3f6af6c86fc5.jpg)
![IMG_20210112_162510](https://user-images.githubusercontent.com/8143724/104335996-39003380-54f4-11eb-9342-8885ac1dc0f1.jpg)

**Comment by dut-iptv** [comment]
@maffiabaas I have found an error in the Ziggo V3/V4 login. Please try again with 0.9.129. If it still not works we should create a seperate issue for this.

@powermarcel10 You will get the same answer as everyone that asks this question on the IPTV Simple GitHub: Use [IPTV Merge](https://www.matthuisman.nz/2019/02/iptv-merge-kodi-add-on.html). 
First setup the Dut-IPTV Simple IPTV Connector addon, than setup IPTV Merge and point it at the playlist.m3u8 and epg.xml in the userdata directory of my addon. 
Add any other playlist/EPG you want to use from other systems.

Ziggo Go's max resolution for any stream in their apps and on their web app is 720p. Max resolution on KPN, NLZiet and T-Mobile is 1080p.

@J-o-h-n-M Your skin does not show the "Description/Plot" text which explains what the options mean. 
It is asking if you want to add radio channels to IPTV Simple. 

The error you recieve seems to indicate your system believes https://dut-epg.github.io/a.channels.zip to be a faulty zipfile.
On what platform are you running the addon?

**Comment by maffiabaas** [comment]
> @maffiabaas I have found an error in the Ziggo V3/V4 login. Please try again with 0.9.129. If it still not works we should create a seperate issue for this.

Login works now, but channels wont. After login i see this error. 
![16104772926378960822991934905386](https://user-images.githubusercontent.com/77290177/104358744-29daaf00-550f-11eb-9171-646bc9e58ac0.jpg)

**Comment by J-o-h-n-M** [comment]
> @J-o-h-n-M Your skin does not show the "Description/Plot" text which explains what the options mean.
> It is asking if you want to add radio channels to IPTV Simple.
> 
> The error you recieve seems to indicate your system believes https://dut-epg.github.io/a.channels.zip to be a faulty zipfile.
> On what platform are you running the addon?

I am running it on the standard Android that is installed on my Sony tv. So in Android I just installed the standard Kodi app.

**Comment by dut-iptv** [comment]
@maffiabaas At least it's progress. Found your next bug. Fixed in 0.9.130, which is already up right now.

**Comment by jbouwh** [comment]
Nlziet plugin works ok. Had to reboot kodi (LibreElec) and logon again after installing the simple iptv connector.

**Comment by maffiabaas** [comment]
> @maffiabaas At least it's progress. Found your next bug. Fixed in 0.9.130, which is already up right now.
> Please relogin before moving on.

I updated and did a re login. Everything fine, but the streams wont start. Afspelen mislukt, een of meerdere items konden niet worden afgespeeld. Controleer het log voor meer informatie over dit bericht.

**Comment by dut-iptv** [comment]
@J-o-h-n-M I found some mentions online about Kodi + Android and bogus BadZipFile errors. I have uploaded version 131 with a fix which hopefully should remedy these errors.

**Comment by J-o-h-n-M** [comment]
> @J-o-h-n-M I found some mentions online about Kodi + Android and bogus BadZipFile errors. I have uploaded version 131 with a fix which hopefully should remedy these errors.

Thanks for the Quick response!
Version 131 works perfect.

**Comment by dut-iptv** [comment]
@maffiabaas Sorry I really messed up Ziggo V3, as mentioned before I can't test on it myself.

Hopefully 132 resolves (some more of) your remaining problems.

**Comment by maffiabaas** [comment]
> @maffiabaas Sorry I really messed up Ziggo V3, as mentioned before I can't test on it myself.
> 
> Hopefully 132 resolves (some more of) your remaining problems.

Thanks For the support, but stil a error. 
![1610481185188252988979983914567](https://user-images.githubusercontent.com/77290177/104365374-36afd080-5518-11eb-9e9e-1c8ff929884d.jpg)

**Comment by dut-iptv** [comment]
@maffiabaas Does everything in the ZiggoGo addon itself work?

Will fix the error in the connector asap.

**Comment by maffiabaas** [comment]
> @maffiabaas Does everything in the ZiggoGo addon itself work?
> 
> Will fix the error in the connector asap.

I can login but cant view anything. Its also says that i dont own movies and series xl (but thats not true). I have tried it also in kodi on windows and there i have the same problem. 
After clicking on a stream i get this error:
2021-01-12 21:09:56.259 T:18784   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.ziggo/?_=play_video&channel=24443942983&id=http%3A%2F%2Fobc1-1-nl-prod.live.dyncdn.horizon.tv%2Fdash%2FNL_000001_019401%2Fmanifest.mpd%26%25%25%26urn%3Aorion%3Amedia%3Astd%3A_csgmCqzfjni&type=channel&_l=.pvr]

**Comment by powermarcel10** [comment]
> @maffiabaas I have found an error in the Ziggo V3/V4 login. Please try again with 0.9.129. If it still not works we should create a seperate issue for this.
> 
> @powermarcel10 You will get the same answer as everyone that asks this question on the IPTV Simple GitHub: Use [IPTV Merge](https://www.matthuisman.nz/2019/02/iptv-merge-kodi-add-on.html).
> First setup the Dut-IPTV Simple IPTV Connector addon, than setup IPTV Merge and point it at the playlist.m3u8 and epg.xml in the userdata directory of my addon.
> Add any other playlist/EPG you want to use from other systems.
> 
> Ziggo Go's max resolution for any stream in their apps and on their web app is 720p. Max resolution on KPN, NLZiet and T-Mobile is 1080p.
> 
> @J-o-h-n-M Your skin does not show the "Description/Plot" text which explains what the options mean.
> It is asking if you want to add radio channels to IPTV Simple.
> 
> The error you recieve seems to indicate your system believes https://dut-epg.github.io/a.channels.zip to be a faulty zipfile.
> On what platform are you running the addon?

Thanks for the suggestion. I will check it out. I'm trying the T Mobile of my heighbours now and it is indeed a lot sharper than the Ziggo streams. So I will consider to switch my subscription as I am free to leave.

**Comment by dut-iptv** [comment]
@maffiabaas Please do the following:
-Update to 137
-Reset the Ziggo Addon from the Settings menu
-Relogin
-Try to play a Live channel and Replay stream again

I have made changes to both the addon and the V3 EPG (on the seperate GitHub where EPG data is stored) which should hopefully help.

**Comment by powermarcel10** [comment]
I am getting an error message for the iptv connector. It is not able to connect the t mobile addon to the simple iptv addon. When I try to do so, I need to select yes or no at the question if I want to add radio channels. No matter is I select yes or no, I am getting this message;

**Comment by atreyuhere** [comment]
I can confirm @powermarcel10 's findings.
Reverting back to .128 fixes the issue.

**Comment by dut-iptv** [comment]
@powermarcel10 @J-o-h-n-M @atreyuhere The fix for J-o-h-n-M probably broke Zip file extracting for others.

Trying a best of all words solution in 138.

**Comment by powermarcel10** [comment]
> @powermarcel10 @J-o-h-n-M @atreyuhere The fix for J-o-h-n-M probably broke Zip file extracting for others.
> 
> Trying a best of all worlds solution in 138.

Sory, still the same.. And for t mobile I am getting a message that I am logged in on to many systems.. I think because I did this process so many times now. But im able to login to a browser. Maybe I need to wait for a while. But using theziggo addon, still getting the same error as earlier.

**Comment by Bubbelb** [comment]
Well, got it running, for the most part. On an LibreELEC x86_64 9.2.6 machine (Freshly installed).
I noticed I had to install dome extra plugins for TV and EPG support. That is working.
I just cannot view a channel through the TV channel list, or via the EPG. Get the following error:
`ERROR: plugin.video.canaldigitaal - local variable 'session_post_data' referenced before assignment
Traceback (most recent call last):
  File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/l5/signals.py", line 29, in throwable
    yield
  File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/l6/router.py", line 94, in dispatch
    function(**params)
  File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/l7/plugin.py", line 27, in decorated_function
    item = f(*args, **kwargs)
  File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/l8/menu.py", line 663, in play_video
    playdata = api_play_url(type=type, channel=channel, id=id, video_data=data, from_beginning=from_beginning, pvr=pvr)
  File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/api.py", line 254, in api_play_url
    download = api_download(url=play_url, type='post', headers=headers, data=session_post_data, json_data=True, return_json=True)
UnboundLocalError: local variable 'session_post_data' referenced before assignment
`

Running the stable 128 version...
Any ideas?

**Comment by maffiabaas** [comment]
New version, no errors. But the simpletv cliënt is empty after using the IPTV connector. Radio is fine.

**Comment by Bubbelb** [comment]
Version 139: All fine and dandy now for Canal Digitaal :)

**Comment by powermarcel10** [comment]
Tried version 139, still errors:

**Comment by dut-iptv** [comment]
@maffiabaas Have you restarted Kodi after the connector setup? Will investigate further after work tonight.

@powermarcel10 See my response in #59. Permanent fix will follow tonight

**Comment by Bubbelb** [comment]
Seems like the Canal Digitaal session is lost during a reboot. Playing a channel fails, until i issue a "Reset Session". Then it all works again. (apart from recording, but that's another subject)

**Comment by dut-iptv** [comment]
@Bubbelb Will try to fix in 140, but you are my beta tester as I can't test it myself.

**Comment by Bubbelb** [comment]
@dut-iptv That's fine. Glad to help.
Fwiw: Please also check the dependencies of the add-ons. The EPG portion is not installed as a dependency (at least for the 128 version) and I also needed to install a IPTV add on from Kodi (I do not recall the exact name, and I don't have access to my Kodi test box, right now.

**Comment by maffiabaas** [comment]
> @maffiabaas Have you restarted Kodi after the connector setup? Will investigate further after work 

Yes i did. Its in the simple IPTV connect app, T-Mobile is doing fine but Ziggo is empty.

**Comment by alannl** [comment]
Nice work!
My amateurishly made add-on uses ism because mpd didn't work well with inputstream, but you fixed that with the proxy.
Can you look at making an addon for film1 some day?

**Comment by powermarcel10** [comment]
@dut-iptv everything is working now! Fantastic! Thanks a lot for your great work and support.

**Comment by dut-iptv** [comment]
@Bubbelb 140 includes a fix to check the validity of the session token and refresh if needed in another way. Please try again with the new version.

The EPG/PVR/TV/Radio part of the addon is supported by the Simple IPTV PVR addon. This addon is only necessary when using the Dut-IPTV Simple IPTV Connector addon and during the setup process this addon is automatically installed. I might add it as a dependency for the connector app in the future to automatically install the Simple IPTV addon during installation of the connector addon instead of during the setup wizard.

@maffiabaas 141 includes a fix for your problems. Please update all addons and reset the connector settings from the home page of the connector addon and then follow the setup wizard from the start.

@powermarcel10 Good to hear your problems are fixed in 140

@alannl Thanks. Creating an addon for Film 1 falls kind of in the same category as Ziggo Sport Totaal (which someone requested previously). Both have seperate apps/sites but only sell their subscriptions through the major cable/fiber/DSL providers and are usually available through the app of these providers. How are you subscribed to Film1? If it is through Ziggo/KPN/Tmobile can't you play these channels through my existing addons?

**Comment by maffiabaas** [comment]
> @maffiabaas 141 includes a fix for your problems. Please update all addons and reset the connector settings from the home page of the connector addon and then follow the setup wizard from the start.
> 
unfortunately still the same problem.  Ziggo does not display any tv channels when going through the setup. Radio does. T-Mobile is working (tv and radio).

**Comment by foxhunt72** [comment]
is er some way to fix the buffering issues, i have a lot of stuttering running in kodi on androidtv, i don't have the same issue with the ziggo go app on the same androidtv setup. thanks in advance and nice work.

**Comment by dut-iptv** [comment]
@foxhunt72 I don't have this problem on any of my test systems (Wired Win x64, Wireless Win x64, Wired NVidia Shield TV), unless Ziggo has insufficient bandwidth (during F1 races for instance). 

Might be that your Android TV device is not powerful enough to run the addon.
Kodi can only decrypt WideVine encrypted streams using software decoding, the Ziggo Go app might be able to use hardware decoding which could be the reason the app works better. 

Hardware decoding in Kodi will probably not be coming any time soon.
I can't do anything about this

**Comment by Bubbelb** [comment]
Yeah! Running on 141 and Canal Digitaal runs fine. Switched to an RPI4 due to some HDMI sound issues.
After a reboot, Canal Digitaal keeps on running, as it should. No reset session needed.

The only thin I observed was a hang of kodi. After a reboot, the date was wrong. That got me into SSL issues (Certificate not yet valid). I don't know the cause. The logs were quiet. Not mutch of errors before and after the hang. Maybe totally unrelated to the Canal Digitaal add-on, but I just mention it to see if someone else has the same isssue... 

Thanks for the great add-on!

**Comment by atreyuhere** [comment]
Iptv simple integration works quite well, one thing I have noticed is that some channels are missing through the simple iptv connector.
They do not show in the channel listings when configuring and they don't show in channel lists. 
They are available and playable through the Ziggo Go addon.

As far as I can tell these are the missing channels from the default channels package:

RTL
Sat1
BBC1 
BBC2
ARD
ZDF

**Comment by powermarcel10** [comment]
I'm back at home and trying the Addon on my Windows 10 pc. I'm getting an error on the T-Mobile login:

![16107119944638920991997332614841](https://user-images.githubusercontent.com/2340835/104724884-9af9ac80-5731-11eb-8764-6d5fa20269a5.jpg)

**Comment by dut-iptv** [comment]
@powermarcel10 Will be fixed in 144

@atreyuhere All these channels don't support replay TV on Ziggo GO, but do support live TV playback. They should be selectable for live TV in the connector, but not for catchup. There is probably a bug in the filtering which removes these channels completely from the connector instead of just disabling catchup. Will investigate and will probably be fixed in 144.

**Comment by atreyuhere** [comment]
Oh yes, you are right. Didn't see the correlation.

**Comment by dut-iptv** [comment]
@powermarcel10 @atreyuhere 144 is released in Beta repo with fixes.

**Comment by atreyuhere** [comment]
Thanks. Updated to .144 (connector version still seems top be .143) and channel without replay are now available in the channel list.
Very nice, Cheers!

**Comment by atreyuhere** [comment]
Quick question: I see a script.module.fuzzywussy dir that doesn't seem to be used. Can I get rid of this module ..?

**Comment by dut-iptv** [comment]
@foxhunt72: I remembered there is a stuttering issue on Android on my Nvidia Shield. This was solved by disabling AC3 from the addon settings, which is the default. Have you by any chance modified this setting?

@All contributers: Thanks for all bug reports and testing. All major issues with 128 and up seem to be fixed. This issue will be closed when 1.0 is released.

**Comment by powermarcel10** [comment]
Thanks????? THANK YOU! You did a really great job here! You fixed every single bug, are very helpfull and proffesional. Thumbs up! I can't wait to test your work on a videoland addon in the future..

**Comment by lengyela89** [comment]
Hi,
First of all, thank you for the plugin, it's really amazing! :)

I modified your ziggo plugin (0.9.139; Leia) to access HorizonGo streaming service in my country (same as ZiggoGo, but can be accessed on slightly different urls). Everything works fine, I only ran into the following problem:

if I open a channel (it doesn't matter which one) then stop it two times then finally open it again on Kodi (open, stop, open, stop, open), the plugin uses all the available slots for the HorizonGo service I have (it is only allowed to watch HorizonGo from at most 3 devices in my country). The plugin opens the stream without any problem, but if i try to watch HorizonGo e.g. from mobile at the same time, it says "I don't have free slot...".

If I restart Kodi, it solves the problem. I have the feeling that maybe somehow the formerly closed streams remain opened?

Thanks for your help!

**Comment by dut-iptv** [comment]
@lengyela89 Nice to hear you were able to create another addon from my base. 
My addons were in turn originally based on the work of MattHuisman, who has created some really awesome addons (such as Disney+).

I hope you did not have too much trouble creating your own alternative for the information that is retrieved from the dut-epg GitHub repo. The (mostly PHP) code that creates the files on that repo are not published at this time.

You are almost correct in your analysis of how the stream/token system works for Liberty Global providers such as Ziggo.
Ziggo has the same limit of 3 concurrent stream.  
It is however not depend on closing Kodi, but on a timer. 
Every token is valid for 150 seconds after which they are automatically invalided and you can request another token.
If you open and close streams really quick it is possibly to use up all 3 tokens with my addons before the first token is automatically invalidated.

I have taken another look at what Ziggo does when you end playback on the website and it seems they invalidate the token immediately when ending playback for a channel/program by calling an API endpoint.
I have recreated this solution in my Ziggo plugin.
The version with this system in place will be available in the beta repo in the coming days (version 150 or higher)

**Comment by meganiekje** [comment]
Hi,

First of all: I love your work, this is the best kodi addon for me in years !!!!
I use LibreElec (kodi18.9) with Ziggo.
The addon works great, but after some time (several days, I put my kodi box into suspend) I see a lot of buffering.
The internet speed drops down to below 10 Mb/s. 
When I SSH into my box, and do: netstat -anp , I see a lot of sockets that have status CLOSE_WAIT.
If I reboot the box, or run this command: 

netstat -anp | grep 192.168.178.3 | grep CLOSE_WAIT | awk '{print $7}' | cut -d \/ -f1 | grep -oE "[[:digit:]]{1,}" | xargs kill 

the internet speed comes back up, and all is fine for some days.
I did try some other addons, and none of them produce so many CLOSE_WAIT sockets.
It seems (please correct me if I'm wrong) the Ziggo Addon does not close the sockets corectly.
Hopefully you can tell me what is wrong here.

Thanks for your great Addon, it is sooooooo much better than using the Ziggo-go app, or ziggo box or the website.

**Comment by Bubbelb** [comment]
Since I had some time playing around with the addon, I experienced two small issues. The first is the same as @atreyuhere had for Ziggo. I have no BBC1 and BBC2. For the German ones, I'm missing ZDF, ARD and WDR. Although WDR is not visible in the browser, only on the set-top-box. SAT1 and RTL are not part of the Canaal Digitaal package, at least of the one I have.

The other problem is that the EPG and Program list is not comletely filled by the IPTV addon. In other words: When I view the live-tv list through the add-on, the full list (ex BBC, etc.) is visible. When I go to the channel list through the TV menu, I only see channel numbers 1 through 34. I have reset the IPTV addon, as well as the Simple IPTV connector, but to no avail.
Oh and the total number of live channels is 74. Replay channels is 25 (In the add-on, that is).

And as a finishing note dor the developer: To add another feather in your backside (as the Dutch sayig goes...), What a great addon this is. I simply love it. Thanx.

**Comment by dut-iptv** [comment]
@meganiekje I have not noticed this issue, but I do not mainly test on a Core/LibreELEC system and don't leave Kodi running for longer periods of time on my testing systems. I have made several adjustments to the proxy system to hopefully beter handle closing of stale connections and I implemented a function to automatically restart the proxy on a timer. This version of the proxy (1.1.0) will be in the repo in the coming days. I hope this will resolve your issues.

@Bubbelb I will look into your issue with missing channels. As said before debugging/testing Canal Digitaal is a bit harder because I don't have an account.

**Comment by dut-iptv** [comment]
@Bubbelb Should be fixed in the next version of the addon. You will have access to a maximum of 104 Live channels and 32 Replay channels (the same as in the Canal Digitaal Web app). All channels should be available in the addon itself and through the Simple IPTV connector. 

Please follow these step when you are on version 150 (not released yet):
-Go to the Canal Digitaal addon -> Settings -> Channel Selection and enable all channels in Live and Replay TV that you want available in the addon and Simple IPTV
-Go to the Simple IPTV Connector and reset your settings and follow the setup wizard again
-Reboot Kodi
-Test

**Comment by atreyuhere** [comment]
I just update from the beta Repo.
The Simple IPTV Connecor (.152) throws an error and cannot be opened for configuration.

**Comment by dut-iptv** [comment]
@atreyuhere Already fixed in 153

**Comment by atreyuhere** [comment]
Certainly is ;)
I will check if an issue i found with the connector < v.15x  is solved with the fixes you have applied.
Replay function stopped functioning altogether after a certain amount of (idle) time and i had to run the connector config again to get it to work.

**Comment by powermarcel10** [comment]
I found 2 possible bugs.

1) For the T-Mobile addon: When the option "force surround sound (when available)" is enabled, I'm only getting an audio stream as you can see here:

![16112572467339193265902314347268](https://user-images.githubusercontent.com/2340835/105402020-2938cb80-5c27-11eb-9157-15ae339f2a1a.jpg)

2) another issue, also only for the T-Mobile addon: for now playing content for live tv there is no thumb available as you can see in the osd:

![16112573910046823863396245562021](https://user-images.githubusercontent.com/2340835/105402200-6ef59400-5c27-11eb-9018-710d8c96d842.jpg)

When I am zapping, the thumb comes availible:

![16112574310351417780166825592142](https://user-images.githubusercontent.com/2340835/105402286-8896db80-5c27-11eb-8f00-59237eb7cbd6.jpg)

**Comment by powermarcel10** [comment]
With the Ziggo addon I'm getting this:

![16112577918743388682231013490354](https://user-images.githubusercontent.com/2340835/105403009-723d4f80-5c28-11eb-8dfa-fb01070a7491.jpg)

**Comment by dut-iptv** [comment]
@powermarcel10 Bug 1 is fixed in service.dutiptv.proxy 1.0.3

Your second problem might be related to the SSL mess up at T-Mobile (they have an invalid SSL certificate since 20-01-2021 because of a (long planned) certificate revocation) which makes their web application unaccessible by systems that force SSL verification (such as most browsers). Images are also retrieved from there which could cause errors when trying to download the images from the domain with the bad certificate.

Please test after https://t-mobiletv.nl/ is available again.

**Comment by powermarcel10** [comment]
Thanks for addressing and fixing the first issue! It's working fine again.

About the other thing, I can't remember if is has working in the past. But I'm sure its not working for at least the last couple of days.. Is that possible considering your explanation?

**Comment by dut-iptv** [comment]
@powermarcel10 You are right the icon thing wasn't related to the T-Mobile SSL outage and was present in multiple addons (but not all). It has to do with my efforts to minimize requests to the providers when the EPG/PVR is used (to speed up changing channels) and I disabled requests to provider info pages when playing back live TV using the PVR because icons and descriptions are already in the XMLTV files. Kodi however just ignores icons in the XMLTV files which makes it necessary to retrieve this information from the providers when changing channels.

In 1.0.0 this will be fixed.

**Comment by dut-iptv** [comment]
Starting with 1.0.0 all Discussions (See https://github.com/dut-iptv/dut-iptv/discussions), Issues (https://github.com/dut-iptv/dut-iptv/issues) and PR's for my Kodi addons will move to the dut-iptv repo. The dut-iptv.github.io repo will only be used as a Kodi repository. 

Closing this thread.

Please continue in https://github.com/dut-iptv/dut-iptv/issues/4
