### ISSUE TITLE
[All] Upcoming 1.0 Release

### ISSUE THREAD

**Issue by dut-iptv** [dut-iptv/dut-iptv.github.io#63]
I intend to release a 1.0 version of the addons in the coming week.
The addons are at a point where I feel they are mature enough to deserve a 1.0 moniker.

Starting from 1.0 I will be making the following changes:

-With the release of Kodi 19 RC1 today I will cease development on Kodi 18. So version 1.0 will be the last release supporting Kodi 18. Kodi 19 brings a lot of exciting new features, of which the most important for my addons is the support for catchup in PVR. Keeping both Kodi 18 on Python 2 and Kodi 19 on Python 3 supported introduces a lot of workarounds which will be removed form versions starting from 1.0

-The dut-iptv.github.io repo will be used as a Kodi repository only. Issues and Pull Requests will be disabled and only files needed to make the addons available from Kodi will remain. Old and Beta versions will remain available and updated.

-Source, Issues, Pull Requests and Discussions will move to the dut-iptv/dut-iptv repo. Releases with changelogs (not for beta versions) will be created there and proper commits tracking will be available 

-I will consider adding additional addons such as Videoland

**Comment by atreyuhere** [comment]
You have created a perfectly usable addon to watch a number of provider's subscription-tv and should be rewarded by all of them in my opinion ;)
Can't wait what v1+ will bring..!

**Comment by dut-iptv** [comment]
@ericvanbeurden No work will be done on changing the interface. 

When you use Simple IPTV PVR and the Dut-IPTV Simple IPTV connector I believe watching LiveTV and ReplayTV (starting from Kodi 19) is pretty easy and intuitive and lots of people have been using the PVR component in Kodi for watching LiveTV using DVB backends for years.

I have zero interest in creating a solution such as Webbieplayer which goes against Kodi's design principles for addons. Because the addons conform to Kodi's design principles some functions will never be as streamlined as specifically designed apps by the providers themselves.

Some advantages of the addons compared to the apps by the providers are the ability to seek in any stream without restriction and for Ziggo the ability to watch stream on VPN/other internet connections (which is blocked in the Android TV app by Ziggo)

**Comment by atreyuhere** [comment]
"No work will be done on changing the interface."

Good :)

**Comment by dut-iptv** [comment]
Starting with 1.0.0 all Discussions (See https://github.com/dut-iptv/dut-iptv/discussions), Issues (https://github.com/dut-iptv/dut-iptv/issues) and PR's for my Kodi addons will move to the dut-iptv repo. The dut-iptv.github.io repo will only be used as a Kodi repository. 

Closing this thread.

Please continue in https://github.com/dut-iptv/dut-iptv/issues/4
