### ISSUE TITLE
[KPN] KPN ITV - Unexpected Error

### ISSUE THREAD

**Issue by Uome** [dut-iptv/dut-iptv.github.io#7]
When trying to log in with my KPN account, I receive the following error:

```
KPN ITV - Unexpected Error

MissingSchema: Invalid URL '/USER/SESSIONS/': No schema supplied. Perhaps you meant http:///USER/SESSIONS/?
```

In case you want more details, can you please point me to the location of the log?

**Comment by dut-iptv** [comment]
Seems something went wrong with downloading the settings file which includes the KPN API URL.
Even if this went wrong this should not give an error though.
Hopefully fixed this in the latest version. Please update to 9.9.37

**Comment by Uome** [comment]
Unfortunately, updating to 9.9.37 didn't solve it. However, there seem to be internal server problems with the web portal currently.

The following KPN related errors occurred in the log:

`ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.kpn/?_=login`
`ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kpn/?_=login) failed`

**Comment by Uome** [comment]
As a follow up on my previous post, the server errors haven been solved, and the web portal has been working fine during the last week. However, the login problems with the add-on have remained. I therefore suspect the login problems to be in the add-on itself.

**Comment by dut-iptv** [comment]
As mentioned in #9  I have enabled further logging for failed login attempts.
Please try again using your Customer number and PIN and report back with the debug log of a failed login attempt
