### ISSUE TITLE
[Ziggo] Error logging in to Ziggo - Check your username and password

### ISSUE THREAD

**Issue by Uome** [dut-iptv/dut-iptv.github.io#8]
Whenever I try to log in to the Ziggo GO add-on with my account, I receive the following message:

_Error Logging in to Ziggo - Check your username and password_

My account works just fine on the Ziggo GO web portal.

The log contains the following errors:

`ERROR: CScriptInvocationManager::ExecuteAsync - Not executing non-existing script C:\Users\XXXX\AppData\Roaming\Kodi\addons\script.navi-x\service.py`
`ERROR: CServiceAddonManager: script.navi-x failed to start`
`ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.ziggo/?_=login`
`ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.ziggo/?_=login) failed`
`ERROR: C:\Users\XXXX\AppData\Roaming\Kodi\addons\script.module.fuzzywuzzy\lib\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')`

**Comment by dut-iptv** [comment]
I have uploaded .39 to the repo with further logging of any failed login attempts.
Please try to login again and report any errors.

If you are still unable to login please report back with the following:
-Launch chrome/firefox on your computer
-Enable Developer console using Ctrl + Shift + I or F12
-Open the network tab
-Browse to https://www.ziggogo.tv/
-Clear the contents of the network tab using the clear button
-Login to Ziggo Go using your credentials
-Find mentions to "session" in the network tab, there will be multiple
-Right click the last "session" entry (should be a POST request) and click "Copy" -> "Copy as Powershell"
-Past in a text editor and replace any mention to your email address and password
-Copy and paste the resulting output here

**Comment by Uome** [comment]
The Ziggo GO add-on is still giving the same error. Below you can find the POST request:


`await fetch("https://web-api-pepper.horizon.tv/oesp/v2/NL/nld/web/session?token=true", {`
`    "credentials": "omit",`
`    "headers": {`
`        "User-Agent": "XXXX",`
`        "Accept": "application/json",`
`        "Accept-Language": "en-US,en;q=0.5",`
`        "Content-Type": "application/json",`
`        "X-Client-Id": "XXXX"`
`    },`
`    "referrer": "https://www.ziggogo.tv/nl/tv/watch-tv.html",`
`    "body": "{\"username\":\"XXXX\",\"password\":\"XXXX\"}",`
`    "method": "POST",`
`    "mode": "cors"`
`});`

**Comment by dut-iptv** [comment]
Thanks for the information.

Is the Kodi debug log after updating the addon more helpful than before?
The status code en JSON response returned by the Ziggo session endpoint should be written to the log in the latest version

**Comment by Uome** [comment]
Is this of any help?

`DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting definitions`
`DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting values`
`DEBUG: plugin.video.ziggo - Attempt 1/2: POST https://web-api-pepper.horizon.tv/oesp/v2/NL/nld/web/session`
`DEBUG: ------ Window Init (DialogConfirm.xml) ------`
` INFO: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY`
`DEBUG: ------ Window Deinit (DialogConfirm.xml) ------`
`ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.ziggo/?_=login`
`WARNING: Attempt to use invalid handle 1`
`DEBUG: Thread waiting 16680 terminating`
`DEBUG: plugin.video.ziggo - SIGNAL: after_dispatch`
`DEBUG: plugin.video.ziggo - SIGNAL: on_close`
` INFO: CPythonInvoker(5, C:\Users\XXXX\AppData\Roaming\Kodi\addons\plugin.video.ziggo\default.py): script successfully run`
`DEBUG: ------ Window Deinit (DialogBusy.xml) ------`
`ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.ziggo/?_=login) failed`
`DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.ziggo/)`
`DEBUG:   ParentPath = [plugin://plugin.video.ziggo/]`
`DEBUG: Loading items: 2, directory: plugin://plugin.video.ziggo/ sort method: 0, ascending: false`
`DEBUG: CAddonDatabase::SetLastUsed[plugin.video.ziggo] took 10 ms`
`DEBUG: Thread BackgroundLoader start, auto delete: false`
`DEBUG: Clearing cached fileitems [plugin://plugin.video.ziggo/]`
`DEBUG: Thread BackgroundLoader 15308 terminating`
`DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.ziggo/)`
`DEBUG:   ParentPath = [plugin://plugin.video.ziggo/]`
`DEBUG: Thread waiting start, auto delete: false`
`DEBUG: CAddonDatabase::SetLastUsed[plugin.video.ziggo] took 9 ms`
`DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin Ziggo GO('plugin://plugin.video.ziggo/','1','','resume:false')`
`DEBUG: CScriptInvocationManager::GetLanguageInvoker - Reusing LanguageInvokerThread 5 for script C:\Users\XXXX\AppData\Roaming\Kodi\addons\plugin.video.ziggo\default.py`
`  INFO: initializing python engine.`
`DEBUG: CPythonInvoker(5, C:\Users\XXXX\AppData\Roaming\Kodi\addons\plugin.video.ziggo\default.py): start processing`
`DEBUG: CPythonInvoker(5, C:\Users\XXXX\AppData\Roaming\Kodi\addons\plugin.video.ziggo\default.py): entering source directory C:\Users\XXXX\AppData\Roaming\Kodi\addons\plugin.video.ziggo`
`DEBUG: CPythonInvoker(5, C:\Users\XXXX\AppData\Roaming\Kodi\addons\plugin.video.ziggo\default.py): instantiating addon using automatically obtained id of "plugin.video.ziggo" dependent on version 2.26.0 of the xbmc.python api`
`DEBUG: plugin.video.ziggo - Router Parsed: '' => home {'_url': ''}`
`DEBUG: plugin.video.ziggo - SIGNAL: before_dispatch`
`DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting definitions`
`DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting values`
`DEBUG: ------ Window Init (DialogBusy.xml) ------`
`DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting definitions`
`DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting values`
`DEBUG: Thread waiting 19528 terminating`
`DEBUG: plugin.video.ziggo - SIGNAL: after_dispatch`
`DEBUG: plugin.video.ziggo - SIGNAL: on_close`
` INFO: CPythonInvoker(5, C:\Users\XXXX\AppData\Roaming\Kodi\addons\plugin.video.ziggo\default.py): script successfully run`
`DEBUG: ------ Window Deinit (DialogBusy.xml) ------`
`DEBUG: Saving fileitems [plugin://plugin.video.ziggo/]`

**Comment by dut-iptv** [comment]
Apparantly in 9.9.39 status code en response was still not correctly logged to the Kodi debug log, this should be fixed in .40.

Please update through Kodi to 9.9.40 and report back with the output of the Kodi debug log after trying to login.
I'm looking for the part of the log right after:

DEBUG: plugin.video.ziggo - Attempt 1/2: POST https://web-api-pepper.horizon.tv/oesp/v2/NL/nld/web/session

**Comment by Uome** [comment]
Logging in seems to work since the last update. However, when selecting Live TV in the add-on, it only presents the options "Back", and "~No Items~".

**Comment by dut-iptv** [comment]
Please try a session reset from settings and report back if channels are showing afterwards

**Comment by Uome** [comment]
Now Live TV works from the Live TV option within the add-on itself. However, watching TV does not yet work through TV option within the KODI main menu. Clicking on one of the channels there, doesn't seem to do anything. The option "Live TV points to Simple IPTV PVR" is selected within the add-on.

**Comment by dut-iptv** [comment]
You can only connect SImple IPTV to Live TV from one of the addons (you had KPN also installed right?)
Try the "Auto setup IPTV" from the settings menu from the addon you want to use for Live TV and reboot Kodi afterwards, then try again.

**Comment by Uome** [comment]
That did the trick, thanks!
