### ISSUE TITLE
[KPN] Feature request - login using email address and password

### ISSUE THREAD

**Issue by Uome** [dut-iptv/dut-iptv.github.io#9]
Would it also be possible to login using my email address and password, instead of subscription number and PIN?

**Comment by dut-iptv** [comment]
I will take a look at implementing this feature and also your login problems with the customer no. and PIN

Would you be able to do the following:
-Launch chrome/firefox on your computer
-Enable Developer console using Ctrl + Shift + I or F12
-Open the network tab
-Browse to https://tv.kpn.com/
-Clear the contents of the network tab using the clear button
-Login to KPN using your credentials (email/password)
-Find a mention to "session" in the network tab, there could be multiple
-Right click the last "session" entry (should be a POST request) and click "Copy" -> "Copy as Powershell"
-Past in a text editor and replace any mentions to your private information e.g. (email address, password, pin)
-Copy and paste the resulting output here or send me an email with that information
-Repeat the above with your customer no. and PIN

**Comment by Uome** [comment]
For logging in using email address and password:

`await fetch("https://api.tv.kpn.com/101/1.2.0/A/nld/pctv/kpn/USER/SESSIONS/", { `
`    "credentials": "include", `
`    "headers": { `
`        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0", `
`        "Accept": "*/*", `
`        "Accept-Language": "en-US,en;q=0.5", `
`        "AVSSite": "http://www.itvonline.nl", `
`        "Content-Type": "application/json", `
`        "X-Xsrf-Token": "null" `
`    }, `
`    "referrer": "https://tv.kpn.com/inloggen", `
`    "body": "{\"credentialsExtAuth\":{\"deviceInfo\":{\"deviceId\":\"******\",\"deviceIdType\":\"DEVICEID\",\"deviceType\":\"PCTV\",\"deviceVendor\":\"Firefox\",\"deviceModel\":\"80.0\",\"deviceFirmVersion\":\"Windows\",\"appVersion\":\"10\"},\"credentials\":{\"loginType\":\"UsernamePassword\",\"username\":\"***@***.***\",\"password\":\"******\",\"appId\":\"KPN\"},\"remember\":\"Y\"}}", `
`    "method": "POST", `
`    "mode": "cors" `
`});`

For whatever reason, logging in using subscription ID and PIN is currently impossible.

**Comment by dut-iptv** [comment]
I have uploaded .38 to the repo.
Within the addon settings you can enable logging in with your email and password.
Please try to login after changing this setting using your credentials and report back if it works.
If it doesn't I have enabled extra logging in the addon to further pinpoint the source of any login errors.

**Comment by Uome** [comment]
Congrats! I can confirm that KPN IPTV is working.
